### model
model_name_or_path: Qwen/Qwen2.5-7B-Instruct
trust_remote_code: true

### method
stage: eata
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: q_proj,v_proj
# deepspeed: examples/deepspeed/ds_z3_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset: db_genmedgpt
template: qwen
cutoff_len: 8192
# max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 128
dataloader_num_workers: 16

# tent
tent_generation_len: 80
# eata
eata_entropy_threshold: 0.4

ttl_threshold: 1
ttl_sample_efficiency_scaler: 0.1
ttl_loss: ppl_ppl_sum

### output
output_dir: saves/qwen25_7b/lora/eata/db/genmedgpt
logging_steps: 10
save_steps: 5000
plot_loss: true
overwrite_output_dir: true
save_only_model: true
report_to: wandb  # choices: [none, wandb, tensorboard, swanlab, mlflow]
run_name: eata_db_genmedgpt
#report_to: none

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
learning_rate: 5e-5
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null
seed: 42
tokenized_path: tokenized_path

### eval
# eval_dataset: alpaca_en_demo
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
