# model
model_name_or_path: /home/yijiexu/LLMWatermark/WM-Open-Source-LLM/models/Llama-2-7b-hf

# method
stage: pt
do_train: true
finetuning_type: full

# ddp
ddp_timeout: 180000000
deepspeed: examples/deepspeed/ds_z3_config.json

# dataset
dataset: aar_k2_en
template: default
cutoff_len: 1024
max_samples: 100000
val_size: 0.1
overwrite_cache: true
preprocessing_num_workers: 16

# output
output_dir: saves/LLaMA2-7B/full/pt/aar/k2/en
logging_steps: 10
save_steps: 20000
plot_loss: true
overwrite_output_dir: true

# train
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
learning_rate: 0.00005
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_steps: 0.1
fp16: true
# bf16: true
save_only_model: true

# eval
per_device_eval_batch_size: 1
evaluation_strategy: steps
eval_steps: 200
