# model
model_name_or_path: /home/yijiexu/LLMWatermark/WM-Open-Source-LLM/LLaMA-Factory/saves/LLaMA2-7B/full/pt/aar/k2/en

# method
stage: sft
do_train: true
finetuning_type: full

# ddp
ddp_timeout: 180000000
deepspeed: examples/deepspeed/ds_z3_config.json

# dataset
dataset: dolly-15k
template: llama2
cutoff_len: 1024
max_samples: 3000
val_size: 0.1
overwrite_cache: true
preprocessing_num_workers: 16

# output
output_dir: saves/LLaMA2-7B/full/sft/aar/k2/en/dolly-15k
logging_steps: 10
save_steps: 1000
plot_loss: true
overwrite_output_dir: true
save_only_model: true

# train
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
learning_rate: 0.00005
num_train_epochs: 10.0
lr_scheduler_type: cosine
warmup_steps: 0.1
fp16: true

# eval
per_device_eval_batch_size: 1
evaluation_strategy: steps
eval_steps: 100
